CREATE TABLE JATEKOS 
(
  FELHASZNALONEV VARCHAR2(20) NOT NULL PRIMARY KEY 
, EMAIL VARCHAR2(20) NOT NULL UNIQUE
, ADMIN NUMBER(1) NOT NULL 
, JELSZO VARCHAR2(20) NOT NULL 
, PONTSZAM VARCHAR2(20) 
, SALT VARCHAR2(20) 
);

CREATE TABLE PARBAJ 
(
  ID NUMBER NOT NULL PRIMARY KEY
, PENDING NUMBER(1) NOT NULL
, ELLENFEL VARCHAR2(20)
,FOREIGN KEY (ELLENFEL) REFERENCES JATEKOS(FELHASZNALONEV)
);

CREATE TABLE VERSENY 
(
  ID NUMBER NOT NULL PRIMARY KEY
, NEV VARCHAR2(20) NOT NULL 
);

CREATE TABLE KERDES 
(
  SZOVEG VARCHAR2(500) NOT NULL PRIMARY KEY
, TEMAKOR VARCHAR2(20) 
, BETUJEL VARCHAR2(1) 
,FOREIGN KEY (TEMAKOR) REFERENCES TEMAKOR(NEV)
,FOREIGN KEY (BETUJEL) REFERENCES BETUJEL(JEL)
);

CREATE TABLE TEMAKOR 
(
  NEV VARCHAR2(20) NOT NULL PRIMARY KEY
);

CREATE TABLE BETUJEL 
(
  JEL VARCHAR2(1) NOT NULL PRIMARY KEY
);

CREATE TABLE KOZOSSEG 
(
  ID NUMBER NOT NULL PRIMARY KEY
, NEV VARCHAR2(20)
);

CREATE TABLE HIRDETES 
(
  ID NUMBER NOT NULL PRIMARY KEY
, CIM VARCHAR2(20) NOT NULL 
, SZOVEG VARCHAR2(200) 
, PLAKAT BLOB 
);

CREATE TABLE FORDULO 
(
  VERSENYID NUMBER 
, KEZDES DATE 
, BESTOF NUMBER NOT NULL
,FOREIGN KEY (VERSENYID) REFERENCES VERSENY(ID)
);

CREATE TABLE UTKOZET 
(
  VERSENYID NUMBER
, KEZDES DATE
, FELHASZNALONEV VARCHAR2(20)
,FOREIGN KEY (VERSENYID) REFERENCES VERSENY(ID)
,FOREIGN KEY (FELHASZNALONEV) REFERENCES JATEKOS(FELHASZNALONEV)
,PRIMARY KEY(VERSENYID,FELHASZNALONEV)
);

CREATE TABLE VALASZ 
(
  SZOVEG VARCHAR2(500) 
, BETUJEL VARCHAR2(1) 
, KERDESSZOVEG VARCHAR2(20)
, FOREIGN KEY (BETUJEL) REFERENCES BETUJEL(JEL)
, FOREIGN KEY (KERDESSZOVEG) REFERENCES KERDES(SZOVEG)
, PRIMARY KEY(SZOVEG, BETUJEL)
);

CREATE TABLE UZENET 
(
  KULDO VARCHAR2(20)
, KOZOSSEG NUMBER 
, IDOPONT DATE NOT NULL
, SZOVEG VARCHAR2(500) 
, FOREIGN KEY (KULDO) REFERENCES JATEKOS(FELHASZNALONEV)
, FOREIGN KEY (KOZOSSEG) REFERENCES KOZOSSEG(ID)
, PRIMARY KEY (KULDO, KOZOSSEG)
);

CREATE TABLE UTKOZETRESZVETEL 
(
  VERSENYID NUMBER 
, FELHASZNALONEV VARCHAR2(20)
, FOREIGN KEY (VERSENYID) REFERENCES VERSENY(ID)
, FOREIGN KEY (FELHASZNALONEV) REFERENCES JATEKOS(FELHASZNALONEV)
, PRIMARY KEY(VERSENYID, FELHASZNALONEV)
);

CREATE TABLE UTKOZETKERDESE 
(
  VERSENYID NUMBER 
, SZOVEG VARCHAR2(500)
, FOREIGN KEY (VERSENYID) REFERENCES VERSENY(ID)
, FOREIGN KEY (SZOVEG) REFERENCES KERDES(SZOVEG)
, PRIMARY KEY(VERSENYID, SZOVEG)
);

CREATE TABLE PARBAJRESZVETEL 
(
  ID NUMBER 
, JATEKOS VARCHAR2(20)
, FOREIGN KEY (ID) REFERENCES PARBAJ(ID)
, FOREIGN KEY (JATEKOS) REFERENCES JATEKOS(FELHASZNALONEV)
, PRIMARY KEY(ID, JATEKOS)
);

CREATE TABLE PARBAJKERDESE 
(
  ID NUMBER 
, SZOVEG VARCHAR2(500)
, FOREIGN KEY (ID) REFERENCES PARBAJ(ID)
, FOREIGN KEY (SZOVEG) REFERENCES KERDES(SZOVEG)
, PRIMARY KEY(ID, SZOVEG)
);

CREATE TABLE KOZOSSEGTAGJA 
(
  FELHASZNALONEV VARCHAR2(20) 
, KOZOSSEG NUMBER
, FOREIGN KEY (FELHASZNALONEV) REFERENCES JATEKOS(FELHASZNALONEV)
, FOREIGN KEY (KOZOSSEG) REFERENCES KOZOSSEG(ID)
,PRIMARY KEY(FELHASZNALONEV, KOZOSSEG)
);








